//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trader
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisseSonuc
    {
        public string SatilanHisseAdi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public decimal Kazanc { get; set; }
        public Nullable<System.DateTime> SatilanTarih { get; set; }
        public int SatilanHisseId { get; set; }
    }
}
