//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hisse
    {
        public int HisseId { get; set; }
        public string HisseAd { get; set; }
        public decimal Fiyat { get; set; }
        public int Adet { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<System.DateTime> AlmaTarihi { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual Kategori Kategori1 { get; set; }
    }
}
